spring:
  datasource:
    url: jdbc:sqlite:dns.db
    driver-class-name: org.sqlite.JDBC
logging:
  level:
    root: info
    com.mrx: debug
    com.mrx.springdnsserver.mapper: debug
  file:
    path: log
dns:
  port: 53
  name: test
  mode: bio
  cfip: 172.67.186.61
mybatis:
  type-aliases-package: com.mrx.springdnsserver.model
  mapper-locations: classpath:mapper/*.xml, com.mrx.springdnsserver.mapper/*
server:
  port: 8080
  address: 0.0.0.0